services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: quickcommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123   # change in production
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_NAME: quickcommerce
      JWT_SECRET: docker_secret_key_change_me
      PORT: 3000
      RAZORPAY_KEY_ID: rzp_test_TCzpDsuYcI2co3       # <-- add your key
      RAZORPAY_KEY_SECRET: mtfoLdoWl4qErOcM40Ejaj61   # <-- add your secret
    depends_on:
      - db

volumes:
  pgdata: